import { Position, PositionsList } from '@src/models/global/global.model';
import type {
  Toast,
  ToastContextValue,
  ToastPositionMapValue,
  ToastProviderProps,
} from '@src/models/toast/toast.model';
import { FC, useCallback, useId, useRef, useState } from 'react';
import ReactDOM from 'react-dom';
import { ToastContext } from './ToastContext';
import { ToastItem } from './toast-item/ToastItem';

export const ToastProvider: FC<ToastProviderProps> = ({ children, id }) => {
  const MAX_TOASTS_PER_GROUP = 5;
  const [toasts, setToasts] = useState<Toast[]>([]);

  /**
   * Adds a new toast to the list of toasts.
   * @param toast - The toast object to add, excluding the 'id' because the id will be autogenerated.
   * @returns The unique ID of the added toast.
   */
  const addToast = useCallback((toast: Omit<Toast, 'id'>) => {
    const id = `$cb-toast-${crypto.randomUUID()}`;
    setToasts((prev) => {
      // Find position for new toast
      const position = toast.position || PositionsList.topEnd;
      // Filter toasts for this position
      const positionToasts = prev.filter(
        (t) => (t.position || PositionsList.topEnd) === position
      );
      // If max or more, remove oldest in this position
      let newPrev = prev;
      if (positionToasts.length >= MAX_TOASTS_PER_GROUP) {
        // Remove the oldest toast in this position
        const oldestId = positionToasts[0].id;
        newPrev = prev.filter((t) => t.id !== oldestId);
      }
      return [...newPrev, { ...toast, id }];
    });
    return id;
  }, []);

  const removeToast = useCallback((id: string) => {
    setToasts((prev) => prev.filter((t) => t.id !== id));
  }, []);

  const clearToasts = useCallback(() => {
    setToasts([]);
  }, []);

  const value: ToastContextValue = {
    toasts,
    addToast,
    removeToast,
    clearToasts,
  };

  // Position mapping
  const positionMap: Record<Position, ToastPositionMapValue> = {
    'top-start': {
      top: 24,
      left: 24,
      alignItems: 'flex-start',
      flexDirection: 'column',
    },
    'top-center': {
      top: 24,
      left: '50%',
      transform: 'translateX(-50%)',
      alignItems: 'center',
      flexDirection: 'column',
    },
    'top-end': {
      top: 24,
      right: 24,
      alignItems: 'flex-end',
      flexDirection: 'column',
    },
    'middle-start': {
      top: '50%',
      left: 24,
      transform: 'translateY(-50%)',
      alignItems: 'flex-start',
      flexDirection: 'column',
    },
    'middle-center': {
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      alignItems: 'center',
      flexDirection: 'column',
    },
    'middle-end': {
      top: '50%',
      right: 24,
      transform: 'translateY(-50%)',
      alignItems: 'flex-end',
      flexDirection: 'column',
    },
    'bottom-start': {
      bottom: 24,
      left: 24,
      alignItems: 'flex-start',
      flexDirection: 'column-reverse',
    },
    'bottom-center': {
      bottom: 24,
      left: '50%',
      transform: 'translateX(-50%)',
      alignItems: 'center',
      flexDirection: 'column-reverse',
    },
    'bottom-end': {
      bottom: 24,
      right: 24,
      alignItems: 'flex-end',
      flexDirection: 'column-reverse',
    },
  };

  // Group toasts by position
  const groupedToasts: Record<Position, Toast[]> = {
    'top-start': [],
    'top-center': [],
    'top-end': [],
    'middle-start': [],
    'middle-center': [],
    'middle-end': [],
    'bottom-start': [],
    'bottom-center': [],
    'bottom-end': [],
  };
  toasts.forEach((toast) => {
    const pos: Position = toast.position || PositionsList.topEnd;
    if (!groupedToasts[pos]) {
      groupedToasts[pos] = [];
    }
    groupedToasts[pos].push(toast);
  });

  const generatedId = useRef(`cb-toast-provider-${useId()}`);

  const toastContainers = Object.entries(groupedToasts).map(
    ([position, items]) => (
      <div
        id={id ?? generatedId.current}
        key={position}
        className={`cb-toast-container cb-toast-container--${position}`}
        style={{
          position: 'fixed',
          zIndex: 9999,
          gap: 12,
          display: 'flex',
          ...positionMap[position as Position],
        }}
      >
        {items.map((toast) => (
          <ToastItem
            key={toast.id}
            {...toast}
            onClose={toast.onClose ?? removeToast}
          >
            {toast.message}
          </ToastItem>
        ))}
      </div>
    )
  );

  return (
    <ToastContext value={value}>
      {children}
      {ReactDOM.createPortal(toastContainers, document.body)}
    </ToastContext>
  );
};
