import type { Toast, ToastContextValue } from '@src/models/toast/toast.model';
import { FC, ReactNode, useCallback, useState } from 'react';
import { ToastContext } from './ToastContext';

export const ToastProvider: FC<{ children: ReactNode }> = ({ children }) => {
  const [toasts, setToasts] = useState<Toast[]>([]);

  /**
   * Adds a new toast to the list of toasts.
   * @param toast - The toast object to add, excluding the 'id' because the id will be autogenerated.
   * @returns The unique ID of the added toast.
   */
  const addToast = useCallback((toast: Omit<Toast, 'id'>) => {
    const id = `$cb-toast-${crypto.randomUUID()}`;
    setToasts((prev) => [...prev, { ...toast, id }]);
    return id;
  }, []);

  const removeToast = useCallback((id: string) => {
    setToasts((prev) => prev.filter((t) => t.id !== id));
  }, []);

  const clearToasts = useCallback(() => {
    setToasts([]);
  }, []);

  const value: ToastContextValue = {
    toasts,
    addToast,
    removeToast,
    clearToasts,
  };

  return <ToastContext value={value}>{children}</ToastContext>;
};
